<?php
$server = "localhost";
$username = "username";
$password = "password";
$database = "music";
$pagetitle = "oYoMusic: Music Collection Software";
$headertitle = "My Music Collection";
$recordspage = 10;
$searchrecordspage = 100;
$pagerange = 9;
$audiosource = "/music/audio";
$imagepath = "/music/images/albums";
$imagepaththumbs = "/music/images/albums/thumbs";
$imagepathartists = "/music/images/artists";
$joomlapath = "/joomla";
?>
