<?php
$server = "localhost";
$username = "username";
$password = "password";
$database = "music";
$pagetitle = "oYoMusic: Music Collection Software";
$headertitle = "My Music Collection";
$recordspage = 10;
$searchrecordspage = 100;
$pagerange = 9;
// take only one of these audio sources:
//$audiosource = "//Server/Music"; // network folder
//$audiosource = "C:/Music"; // local windows folder
//$audiosource = "file:///Music"; // local linux folder
//$audiosource = "/audio"; // web root folder
$audiosource = "audio"; // web project folder (this project)
$imagepath = "images/albums";
$imagepaththumbs = "images/albums/thumbs";
$imagepathartists = "images/artists";
$joomlapath = "/joomla";
$catraxxdatabasepath = "C:\Users\Someone\Documents\Music\collection.mdb";
$catraxxaudiosource = "Q:\Music";
?>
